// Generated by CoffeeScript 1.6.1

(function(factory) {
  if (typeof exports === "object") {
    return module.exports = factory(require("underscore"));
  } else if (typeof define === "function" && define.amd) {
    return define(["underscore"], factory);
  }
})(function(_) {
  var manager, settings;
  settings = {};
  return manager = {
    init: function(key, data) {
      var currentData, _ref;
      currentData = settings[key] || {};
      settings((_ref = _.extend(data, currentData), key = _ref[0], _ref));
    },
    set: function(key, data) {
      settings((key = data[0], data));
    },
    extend: function(key, data) {
      var currentData, _ref;
      currentData = settings[key] || {};
      settings((_ref = _.extend(currentData, data), key = _ref[0], _ref));
    },
    get: function(key, valueIfMissing) {
      return settings[key] || valueIfMissing;
    },
    _raw: function() {
      return settings;
    }
  };
});
